# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
gems: [jekyll-paginate]

# Setup
title:            The bots and us
tagline:          'Robotics blog by David Landry'
description:      'My work as a master''s student in robotics'

url:              http://davidlandry.xyz
baseurl:          /

author:
  name:           'David Landry'
  url:            https://twitter.com/davidlandry93

paginate:         5
